server:
  # Puerto principal del Monolito
  port: 8080

spring:
  application:
    name: GhostFollowCore

  # ----------------------------------------
  # 1. CONFIGURACIÓN DE BASE DE DATOS
  # ----------------------------------------
  datasource:
    url: jdbc:postgresql://localhost:5433/ghostfollowdb
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ----------------------------------------
  # 2. CONFIGURACIÓN DE CORREO
  # ----------------------------------------
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  main:
    log-startup-info: false

